# Generated by Django 4.2.9 on 2024-02-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='is_patient',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('P', 'Patient'), ('D', 'Doctor')], default='P', max_length=1),
        ),
    ]
