# Generated by Django 4.2.9 on 2024-02-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0002_remove_userdetails_is_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Doctor', 'Doctor')], default='Not Mentioned', max_length=10),
        ),
    ]
