# Generated by Django 4.2.9 on 2024-02-15 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_alter_blogpost_category_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='is_draft',
            new_name='draft',
        ),
    ]
