# Generated by Django 4.2.9 on 2024-02-21 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0010_rename_appointment_appointmentform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentform',
            options={'ordering': ['date_of_appointment', 'start_time_of_appointment']},
        ),
    ]
