# Generated by Django 4.2.9 on 2024-02-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0011_alter_appointmentform_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentForm',
            new_name='Appointment',
        ),
    ]
